# Generated by Django 4.1.7 on 2023-02-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_profile', models.CharField(max_length=256, null=True)),
                ('company_name', models.CharField(max_length=256, null=True)),
                ('employment_location', models.CharField(max_length=256, null=True)),
                ('employment_situation', models.CharField(max_length=256, null=True)),
                ('salary_range', models.CharField(max_length=256, null=True)),
                ('offer_text', models.TextField()),
                ('display_salary', models.BooleanField(null=True)),
                ('g_token', models.TextField()),
            ],
        ),
    ]
